### PR TITLE
added dependency deprecated

### PR DESCRIPTION
**Pull request by annescharf**
Dear Peter,
your App was giving an error due to an update of the translator App. I made a pull request to solve the error. If you could accept the PR, make a new release and update the App on MoveApps, that would be great. 
Thank you!
Anne

### CODE REVIEW

**Comment by kulits2** [comment]
Thanks for the PR, @annescharf. I merged it, fixed another dependency, and submitted a new app version.

However, it looks like `movingpandas` has also introduced breaking changes in https://github.com/movingpandas/movingpandas/commit/e9f50e4a35a95e58ec602f22bf9c0c4eaa605fa3: https://github.com/kulits2/3D-BKDE/actions/runs/10749917922/job/29815412125#step:4:1438 `AttributeError: 'Trajectory' object has no attribute 'traj_id_col_name'`

What version of `movingpandas` is supported by the MoveApps ecosystem? Should I downgrade `movingpandas` to align with the demo `pkl` file found in the app template repo or is there an updated `pkl`?

**Comment by annescharf** [comment]
Hi @kulits2, this might be related to some changes that we needed to do in the App that translates from R to Python. Have a look at this documentation: https://docs.moveapps.org/#/movingPandas_colnames
Basically the column names of the track id and the timestamps are not fixed anymore. In the documentation above we explain how to deal with this. If you continue having issues, let me know and we find out together what the issue might be. Thank you!
